using System.Text;
using System.Text.Json;

namespace HexenSharp;

/// <summary>
/// Map files outside the game: play-testing a .hxm straight from the command line (reloading it whenever it's
/// saved, e.g. from the HTML editor in tools/editor), checking one, and exporting the built-in maps.
/// </summary>
public static class MapFiles
{
    /// <summary>Reads and parses a map file; null with a reason on failure.</summary>
    public static MapDoc TryLoad(string path, out string error)
    {
        error = null;
        try
        {
            var doc = MapDoc.Parse(File.ReadAllText(path));
            if (!doc.Cells.Contains('@')) { error = "the map has no player start (@)"; return null; }
            return doc;
        }
        catch (Exception e) { error = e.Message; return null; }
    }

    /// <summary>--check-map: prints the editor's checks for a map; exit code 1 if it can't be played.</summary>
    public static int Check(string path)
    {
        MapDoc doc;
        try { doc = MapDoc.Parse(File.ReadAllText(path)); }
        catch (Exception e) { Console.WriteLine("! " + e.Message); return 1; }
        var issues = doc.Validate();
        foreach (var i in issues) Console.WriteLine(i);
        if (issues.Count == 0) Console.WriteLine("ok");
        return issues.Any(i => i.StartsWith("!")) ? 1 : 0;
    }

    /// <summary>--export-maps: writes every built-in hub map as a .hxm file, to open as a template.</summary>
    public static int Export(string dir)
    {
        Directory.CreateDirectory(dir);
        foreach (var def in Maps.Hub)
        {
            var path = Path.Combine(dir, MapDoc.FileName(def.Name));
            File.WriteAllText(path, MapDoc.FromDef(def).Serialize());
            Console.WriteLine("wrote " + path);
        }
        return 0;
    }

    /// <summary>The built-in maps as a script the HTML editor loads for its "Built-in maps" menu.</summary>
    public static string BuiltinMapsJs()
    {
        var json = new JsonSerializerOptions { Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping };
        string Js(string v) => JsonSerializer.Serialize(v, json);
        var sb = new StringBuilder();
        sb.Append("// Generated by `dotnet run -- --export-editor-maps` from src/Level.cs. Do not edit by hand.\n");
        sb.Append("window.HEXEN_BUILTIN_MAPS = [\n");
        foreach (var def in Maps.Hub)
        {
            string text = MapDoc.FromDef(def).Serialize();
            sb.Append("  { name: ").Append(Js(def.Name))
              .Append(", file: ").Append(Js(MapDoc.FileName(def.Name)))
              .Append(", text: ").Append(Js(text)).Append(" },\n");
        }
        sb.Append("];\n");
        return sb.ToString();
    }

    /// <summary>The repository root (the folder with HexenSharp.csproj), found by walking up from the build output.</summary>
    public static string RepoRoot()
    {
        for (var d = new DirectoryInfo(AppContext.BaseDirectory); d != null; d = d.Parent)
            if (File.Exists(Path.Combine(d.FullName, "HexenSharp.csproj"))) return d.FullName;
        return null;
    }

    public static string EditorMapsPath => RepoRoot() is { } root ? Path.Combine(root, "tools", "editor", "builtin-maps.js") : null;

    /// <summary>--export-editor-maps: refreshes tools/editor/builtin-maps.js after changing the built-in maps.</summary>
    public static int ExportEditorMaps()
    {
        var path = EditorMapsPath;
        if (path == null) { Console.WriteLine("can't find the repository (HexenSharp.csproj)"); return 1; }
        File.WriteAllText(path, BuiltinMapsJs());
        Console.WriteLine("wrote " + path);
        return 0;
    }
}

/// <summary>Watches a map file and reloads the play-test when it changes.</summary>
public sealed class MapWatcher
{
    public readonly string Path;
    DateTime _stamp;
    float _poll;

    public MapWatcher(string path)
    {
        Path = System.IO.Path.GetFullPath(path);
        _stamp = Stamp();
    }

    DateTime Stamp() => File.Exists(Path) ? File.GetLastWriteTimeUtc(Path) : DateTime.MinValue;

    /// <summary>Checks the file about twice a second; returns true when it reloaded the map.</summary>
    public bool Poll(Game g, float dt)
    {
        _poll -= dt;
        if (_poll > 0) return false;
        _poll = 0.5f;
        var now = Stamp();
        if (now == _stamp) return false;
        _stamp = now;
        // only while play-testing: don't yank the player out of a menu
        if (!g.TestingMap || g.Mode is not (GameMode.Playing or GameMode.Dead)) return false;
        var doc = MapFiles.TryLoad(Path, out var error);
        if (doc == null) { g.Say("Can't reload the map: " + error); return false; }
        g.ReloadTest(doc.ToDef());
        return true;
    }
}
